




#pragma mark - Stable (Objects) -




//These probably won't need to be updated... but just in case...


int RBX_INSTANCE_SELF_OFFSET = 0x8;
int RBX_INSTANCE_CLASS_INFO_OFFSET = 0x18;
int RBX_INSTANCE_NAME_OFFSET = 0x40;
int RBX_INSTANCE_CHILDREN_OFFSET = 0x48;
int RBX_INSTANCE_PARENT_OFFSET = 0x58;






#pragma mark - Volatile (Objects) -





/*
 Join https://www.roblox.com/games/5332389196/Hack-Tests to update these. (You will not need libESP.dylib injected)
 Call 'find_object_offsets()' to get these.
 */



int RBX_PLACEID_OFFSET = 0x3b50f10;
int RBX_TEAM_BRICKCOLOR_OFFSET = 0xb4;
int RBX_MODEL_PRIMARYPART_OFFSET = 0x178;
int RBX_INTVALUE_VALUE_OFFSET = 0xb0;
int RBX_CAMERA_CFRAME_OFFSET = 0xe4;
int RBX_CAMERA_CAMERASUBJECT_OFFSET = 0x260;
int RBX_CAMERA_FIELDOFVIEW_OFFSET = 0x274;
int RBX_PLAYERS_MAXPLAYERS_OFFSET = 0x1e0;
int RBX_PLAYER_CHARACTER_OFFSET = 0xd0;
int RBX_PLAYER_TEAM_OFFSET = 0x120;
int RBX_SKY_MOONTEXTUREID_OFFSET = 0x158;
int RBX_PLAYER_DISPLAYNAME_OFFSET = 0x1a8;
int RBX_HUMANOID_DISPLAYNAME_OFFSET = 0x288;
int RBX_DATAMODEL_JOBID_OFFSET = 0x408;
int RBX_TEXTLABEL_TEXT_OFFSET = 0x8a0;
int RBX_BASEPART_PROPERTIES_OFFSET = 0x128;
int RBX_BASEPART_PROPERTIES_CFRAME_OFFSET = 0x118;
int RBX_BASEPART_PROPERTIES_GRAVITY_OFFSET = 0x110;
int RBX_BASEPART_PROPERTIES_VELOCITY_OFFSET = 0x148;
int RBX_BASEPART_PROPERTIES_ROTVELOCITY_OFFSET = 0x154;
int RBX_BASEPART_PROPERTIES_SIZE_OFFSET = 0x270;
int RBX_LIGHTING_FOGEND_OFFSET = 0x4d0;
int RBX_LIGHTING_CLOCKTIME_TICK_OFFSET = 0x139;
int RBX_LIGHTING_BRIGHTNESS_OFFSET = 0x560;
int RBX_LIGHTING_AMBIENT_OFFSET = 0x564;
int RBX_FRAME_VISIBLE_OFFSET = 0x5ac;
int RBX_BASEPART_PROPERTIES_CANCOLLIDE_OFFSET = 0x2cf;
int RBX_PLAYER_MOUSE_OFFSET = 0x800;







#pragma mark - Volatile (Functions) -





//Call 'find_function_offsets()' to get these.

/*
int RBX_INSTANCE_PARENT_SETTER_METHOD_OFFSET = 0x13239b0;
int RBX_HUMANOID_WALKSPEED_SETTER_METHOD_OFFSET = 0x5bbb1a;
int RBX_HUMANOID_WALKSPEED_GETTER_METHOD_OFFSET = 0x5bbb04;
int RBX_HUMANOID_JUMPPOWER_SETTER_METHOD_OFFSET = 0x5bbbde;
int RBX_TOOL_ACTIVATE_METHOD_OFFSET = 0x1250c60;
int RBX_HUMANOID_HEALTH_GETTER_METHOD_OFFSET = 0x5bb804;
int RBX_HUMANOID_HEALTH_SETTER_METHOD_OFFSET = 0x5bb81a;
int RBX_WORKSPACE_GETSERVERTIMENOW_METHOD_OFFSET = 0x12d57f6;
int RBX_BASEPART_ASSEMBLYLINEARVELOCITY_SETTER_METHOD_OFFSET = 0x10bf882;
int RBX_BASEPART_ASSEMBLYLINEARVELOCITY_GETTER_METHOD_OFFSET = 0x10bf758;
int RBX_REMOTEEVENT_FIRESERVER_METHOD_OFFSET = 0x1122056;
int RBX_REMOTEFUNCTION_INVOKESERVER_METHOD_OFFSET = 0x11216de;
int RBX_BASEPART_ANCHORED_SETTER_METHOD_OFFSET = 0x10d07e0;
*/

int RBX_INSTANCE_PARENT_SETTER_METHOD_OFFSET = 0xe89c;
int RBX_HUMANOID_WALKSPEED_SETTER_METHOD_OFFSET = 0x579da8;
int RBX_HUMANOID_WALKSPEED_GETTER_METHOD_OFFSET = 0x579d94;
int RBX_HUMANOID_JUMPPOWER_SETTER_METHOD_OFFSET = 0x579e70;
int RBX_TOOL_ACTIVATE_METHOD_OFFSET = 0x700;
int RBX_HUMANOID_HEALTH_GETTER_METHOD_OFFSET = 0x579a84;
int RBX_HUMANOID_HEALTH_SETTER_METHOD_OFFSET = 0x579a98;
int RBX_WORKSPACE_GETSERVERTIMENOW_METHOD_OFFSET = 0x1257184;
int RBX_BASEPART_ASSEMBLYLINEARVELOCITY_SETTER_METHOD_OFFSET = 0x1038d08;
int RBX_BASEPART_ASSEMBLYLINEARVELOCITY_GETTER_METHOD_OFFSET = 0x1038c18;
int RBX_REMOTEEVENT_FIRESERVER_METHOD_OFFSET = 0x109e44c;
int RBX_REMOTEFUNCTION_INVOKESERVER_METHOD_OFFSET = 0x109db00;
int RBX_MOUSE_HIT_GETTER_METHOD_OFFSET = 0x12f5328;
int RBX_BASEPART_ANCHORED_GETTER_METHOD_OFFSET = 0x1050050;
