




#pragma mark - Stable (Objects) -


//These probably won't need to be updated... but just in case...


int RBX_INSTANCE_SELF_OFFSET = 0x8;
int RBX_INSTANCE_CLASS_INFO_OFFSET = 0x18;
int RBX_INSTANCE_NAME_OFFSET = 0x40;
int RBX_INSTANCE_CHILDREN_OFFSET = 0x48;
int RBX_INSTANCE_PARENT_OFFSET = 0x58;






#pragma mark - Volatile (Objects) -





/*
 Join https://www.roblox.com/games/5332389196/Hack-Tests to update these. (You will not need libESP.dylib injected)
 Call 'find_object_offsets(task)' to get these.
 */




int RBX_PLACEID_OFFSET = 0x3a7ca38;

int RBX_INTVALUE_VALUE_OFFSET = 0xa8;
int RBX_MODEL_PRIMARYPART_OFFSET = 0x170;
int RBX_TEAM_BRICKCOLOR_OFFSET = 0xac;
int RBX_PLAYER_ACCOUNTAGE_OFFSET = 0x79c;
int RBX_PLAYER_TEAM_OFFSET = 0x128;
int RBX_PLAYER_CHARACTER_OFFSET = 0xd8;
int RBX_PLAYER_RESPAWNLOCATION_OFFSET = 0x158;
int RBX_PLAYER_LAST_INPUT_TIMESTAMP_OFFSET = 0x790;
int RBX_PART_PROPERTIES_OFFSET = 0x120;
int RBX_PART_PROPERTIES_GRAVITY_OFFSET = 0x110;
int RBX_PART_PROPERTIES_CFRAME_OFFSET = 0x118;
int RBX_PART_PROPERTIES_VELOCITY_OFFSET = 0x148;
int RBX_PART_PROPERTIES_ROTVELOCITY_OFFSET = 0x154;
int RBX_DATAMODEL_JOBID_OFFSET = 0x410;
int RBX_PART_RGB_COLOR_OFFSET = 0x150;
int RBX_PART_PROPERTIES_SIZE_OFFSET = 0x270;
int RBX_PART_PROPERTIES_CANCOLLIDE_OFFSET = 0x2cf;
int RBX_CAMERA_CFRAME_0_OFFSET = 0xdc;
int RBX_CAMERA_CAMERA_SUBJECT_OFFSET = 0x220;
int RBX_CAMERA_FOV_OFFSET = 0x234;
int RBX_PLAYER_DISPLAYNAME_OFFSET = 0x1b0;
int RBX_HUMANOID_DISPLAYNAME_OFFSET = 0x398;
int RBX_TEXTLABEL_TEXT_OFFSET = 0x898;
int RBX_HUMANOID_MOVEDIRECTION_OFFSET = 0x2b8;
int RBX_HUMANOID_ENCRYPTED_HEALTH_OFFSET = 0x308;
int RBX_HUMANOID_ENCRYPTED_MAXHEALTH_OFFSET = 0x380;
int RBX_TOOL_CANBEDROPPED_OFFSET = 0x365;
int RBX_FRAME_VISIBLE_OFFSET = 0x5b4;
int RBX_LIGHTING_FOGEND_OFFSET = 0x12c;
int RBX_PLAYERS_RESPAWN_TIME_OFFSET = 0x134;
int RBX_LIGHTING_BRIGHTNESS_OFFSET = 0x150;
int RBX_LIGHTING_AMBIENT_OFFSET = 0x154;
int RBX_PLAYERS_MAXPLAYERS_OFFSET = 0x1e0;





#pragma mark - Volatile (Functions) -


//Call 'find_function_offsets(task)' to get these.

int RBX_INSTANCE_PARENT_SETTER_METHOD_OFFSET = 0xdad820;
int RBX_HUMANOID_WALKSPEED_SETTER_METHOD_OFFSET = 0x6ef772;
int RBX_HUMANOID_JUMPPOWER_SETTER_METHOD_OFFSET = 0x6ef836;
int RBX_TOOL_ACTIVATE_METHOD_OFFSET = 0x118fbfc;
int RBX_HUMANOID_HEALTH_GETTER_METHOD_OFFSET = 0x6ef45a;
