


RBX_CREATE_BASIC_PROPERTY_GET_FUNCTION(intvalue, value, uint64_t, RBX_INTVALUE_VALUE_OFFSET)
RBX_CREATE_BASIC_PROPERTY_SET_FUNCTION(intvalue, value, uint64_t, RBX_INTVALUE_VALUE_OFFSET)

RBX_CREATE_BASIC_PROPERTY_GET_FUNCTION(numbervalue, value, double, RBX_INTVALUE_VALUE_OFFSET)
RBX_CREATE_BASIC_PROPERTY_SET_FUNCTION(numbervalue, value, double, RBX_INTVALUE_VALUE_OFFSET)

RBX_CREATE_BASIC_PROPERTY_GET_FUNCTION(objectvalue, value, vm_address_t, RBX_INTVALUE_VALUE_OFFSET)
RBX_CREATE_BASIC_PROPERTY_SET_FUNCTION(objectvalue, value, vm_address_t, RBX_INTVALUE_VALUE_OFFSET)

RBX_CREATE_BASIC_PROPERTY_GET_FUNCTION(boolvalue, value, bool, RBX_INTVALUE_VALUE_OFFSET)
RBX_CREATE_BASIC_PROPERTY_SET_FUNCTION(boolvalue, value, bool, RBX_INTVALUE_VALUE_OFFSET)

RBX_CREATE_BASIC_STRING_PROPERTY_GET_FUNCTION(stringvalue, value, RBX_STRINGVALUE_VALUE_OFFSET)
