
#define RBX_PLACE_ID_OFFSET 0x38ef260
#define RBX_CAMERA_CFRAME_0_OFFSET 0x154 // keep the first
#define RBX_CAMERA_CAMERA_SUBJECT_OFFSET 0x298
#define RBX_CAMERA_FOV_OFFSET 0x2ac
#define RBX_PLAYER_CHARACTER_OFFSET 0x110
#define RBX_PLAYER_TEAM_OFFSET 0x160
#define RBX_PART_PROPERTIES_OFFSET 0x168 // keep the first
#define RBX_PART_PROPERTIES_GRAVITY_OFFSET 0x110 // keep the first
#define RBX_PART_PROPERTIES_CFRAME_OFFSET 0x118 // keep the first
#define RBX_PART_PROPERTIES_SIZE_OFFSET 0x270  // keep the first
#define RBX_STRING_VALUE_SHORT_VALUE_OFFSET 0xf0
#define RBX_INT_VALUE_VALUE_OFFSET 0xf0
#define RBX_TEXT_LABEL_SHORT_TEXT_OFFSET 0xa30 // keep the first

